@startuml
'https://plantuml.com/sequence-diagram

title Simple auth flow

autonumber

actor User
participant Auth as "Auth site"
database AC as "Authority Center"

User -> Auth : login(login)
Auth -> AC : getKeyPair(login)
AC --> Auth : <public, f(private)>

Auth --> User : pub(nonce), f(private)
User -> Auth : private(public(nonce))
note right
    f = f^-1= hash(psw) xor private
end note

Auth --> User : signed auth token


@enduml